### ISSUE TITLE
Failing to pip install on the Mac with build error

### ISSUE THREAD

**Issue by NathanBWaters** [openai/retro#111]
## Issue summary

Running inside a virtualenv and I run `pip install gym-retro-0.5.6`.  I get the following error:
```
    copying data/Venture-Atari2600/Start.state -> build/lib.macosx-10.13-intel-2.7/retro/data/Venture-Atari2600
    copying data/Venture-Atari2600/metadata.json -> build/lib.macosx-10.13-intel-2.7/retro/data/Venture-Atari2600
    copying data/Venture-Atari2600/data.json -> build/lib.macosx-10.13-intel-2.7/retro/data/Venture-Atari2600
    copying data/Venture-Atari2600/scenario.json -> build/lib.macosx-10.13-intel-2.7/retro/data/Venture-Atari2600
    copying data/Venture-Atari2600/rom.sha -> build/lib.macosx-10.13-intel-2.7/retro/data/Venture-Atari2600
    creating build/lib.macosx-10.13-intel-2.7/retro/data/Berzerk-Atari2600
    copying data/Berzerk-Atari2600/Start.state -> build/lib.macosx-10.13-intel-2.7/retro/data/Berzerk-Atari2600
    copying data/Berzerk-Atari2600/metadata.json -> build/lib.macosx-10.13-intel-2.7/retro/data/Berzerk-Atari2600
    copying data/Berzerk-Atari2600/data.json -> build/lib.macosx-10.13-intel-2.7/retro/data/Berzerk-Atari2600
    copying data/Berzerk-Atari2600/scenario.json -> build/lib.macosx-10.13-intel-2.7/retro/data/Berzerk-Atari2600
    copying data/Berzerk-Atari2600/rom.sha -> build/lib.macosx-10.13-intel-2.7/retro/data/Berzerk-Atari2600
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_p/vzxyl6zn6sng4y449kg3t8980005xp/T/pip-install-rLNYWG/gym-retro/setup.py", line 77, in <module>
        use_scm_version=use_scm_version
      File "/Users/nwaters/code/virtualenv/rl/lib/python2.7/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/nwaters/code/virtualenv/rl/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/_p/vzxyl6zn6sng4y449kg3t8980005xp/T/pip-install-rLNYWG/gym-retro/setup.py", line 34, in run
        suffix = super(CMakeBuild, self).get_ext_filename('')
    TypeError: must be type, not classobj

    ----------------------------------------
Command "/Users/nwaters/code/virtualenv/rl/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_p/vzxyl6zn6sng4y449kg3t8980005xp/T/pip-install-rLNYWG/gym-retro/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_p/vzxyl6zn6sng4y449kg3t8980005xp/T/pip-record-v0fDJB/install-record.txt --single-version-externally-managed --compile --install-headers /Users/nwaters/code/virtualenv/rl/include/site/python2.7/gym-retro" failed with error code 1 in /private/var/folders/_p/vzxyl6zn6sng4y449kg3t8980005xp/T/pip-install-rLNYWG/gym-retro/
```

## System information

- macOS High Sierra 10.13.6
- Python 2.7.10
- gym-retro-0.5.6
- pip 18.1

I see the the docs all state `pip3 install gym-retro`.   Is it expected for `pip` not to work then?

**Comment by endrift** [comment]
Retro does not support python 2.7.

**Comment by NathanBWaters** [comment]
Understood, thank you.
