### ISSUE TITLE
'sudo pip3 install -e' fails

### ISSUE THREAD

**Issue by MPJim** [openai/retro#119]
## Issue summary

This is the Output I get when entering the command:

```
Obtaining file:///home/marco/gym-retro
Collecting gym (from gym-retro==0.6.1.dev35+gabb5aca)
Collecting numpy>=1.10.4 (from gym->gym-retro==0.6.1.dev35+gabb5aca)
  Using cached https://files.pythonhosted.org/packages/f5/bf/4981bcbee43934f0adb8f764a1e70ab0ee5a448f6505bd04a87a2fda2a8b/numpy-1.16.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting requests>=2.0 (from gym->gym-retro==0.6.1.dev35+gabb5aca)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting six (from gym->gym-retro==0.6.1.dev35+gabb5aca)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting scipy (from gym->gym-retro==0.6.1.dev35+gabb5aca)
  Using cached https://files.pythonhosted.org/packages/67/e6/6d4edaceee6a110ecf6f318482f5229792f143e468b34a631f5a0899f56d/scipy-1.2.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyglet>=1.2.0 (from gym->gym-retro==0.6.1.dev35+gabb5aca)
  Using cached https://files.pythonhosted.org/packages/1c/fc/dad5eaaab68f0c21e2f906a94ddb98175662cc5a654eee404d59554ce0fa/pyglet-1.3.2-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.0->gym->gym-retro==0.6.1.dev35+gabb5aca)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.0->gym->gym-retro==0.6.1.dev35+gabb5aca)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.0->gym->gym-retro==0.6.1.dev35+gabb5aca)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0->gym->gym-retro==0.6.1.dev35+gabb5aca)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting future (from pyglet>=1.2.0->gym->gym-retro==0.6.1.dev35+gabb5aca)
Installing collected packages: numpy, certifi, urllib3, idna, chardet, requests, six, scipy, future, pyglet, gym, gym-retro
  Running setup.py develop for gym-retro
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/marco/gym-retro/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
    running develop
    running egg_info
    writing gym_retro.egg-info/PKG-INFO
    writing dependency_links to gym_retro.egg-info/dependency_links.txt
    writing requirements to gym_retro.egg-info/requires.txt
    writing top-level names to gym_retro.egg-info/top_level.txt
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.a' found anywhere in distribution
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*-version' found under directory 'retro/cores'
    writing manifest file 'gym_retro.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at /home/marco/.local/lib/python3.6/site-packages/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
    Call Stack (most recent call first):
      /home/marco/.local/lib/python3.6/site-packages/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
      /home/marco/.local/lib/python3.6/site-packages/cmake/data/share/cmake-3.13/Modules/FindZLIB.cmake:114 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:49 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/marco/gym-retro/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/marco/gym-retro/setup.py", line 90, in <module>
        **kwargs
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/marco/gym-retro/setup.py", line 53, in run
        subprocess.check_call([cmake_exe, '.', '-G', 'Unix Makefiles', build_type, pyext_suffix, pylib_dir, python_executable])
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/marco/.local/bin/cmake', '.', '-G', 'Unix Makefiles', '', '-DPYEXT_SUFFIX:STRING=.cpython-36m-x86_64-linux-gnu.so', '', '-DPYTHON_EXECUTABLE:STRING=/usr/bin/python3']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/marco/gym-retro/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /home/marco/gym-retro/
```

## System information

- [Ubuntu 18.04]
- [Python 3.7.1]
- [0.6.1]

**Comment by endrift** [comment]
`apt-get install zlib1g-dev` and see if that fixes it.

**Comment by christopherhesse** [comment]
Closing due to inactivity.

**Comment by codeclassifiers** [comment]
`zlib1g-dev` installation as pointed out by @endrift fixed the problem for me

**Comment by christopherhesse** [comment]
Thanks @codeclassifiers! I've updated the docs: https://github.com/openai/retro/commit/bd545a629f9c74f116883920bff9650233b5f80e
