### ISSUE TITLE
Installation failed while executing pip3 install -e .

### ISSUE THREAD

**Issue by seungjuchae** [openai/retro#129]
## Issue summary
1. made a virtualenv for the project and activated it
2. git cloned the above retro platform 
```git clone --recursive https://github.com/openai/retro.git gym-retro```
3. downloaded the latest CMake from the official website and checked the checkbox to tell CMake 
    to add itself to the system PATH(path environment variable)
   (also used ```pip3 install cmake``` on cmd) 
4. ```cd gym-retro```  to go inside the directory
5. ```pip3 install -e .``` and Errors with CMake occures

### Errors
```
C:\Users\Seung Ju\Desktop\Programming\Side_Projects\AI\sonic_env\gym-retro>pip3 install -e .
Obtaining file:///C:/Users/Seung%20Ju/Desktop/Programming/Side_Projects/AI/sonic_env/gym-retro
Requirement already satisfied: gym in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from gym-retro==0.6.1.dev52+g85e3de5) (0.11.0)
Requirement already satisfied: numpy>=1.10.4 in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from gym->gym-retro==0.6.1.dev52+g85e3de5) (1.15.4)
Requirement already satisfied: scipy in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from gym->gym-retro==0.6.1.dev52+g85e3de5) (1.2.1)
Requirement already satisfied: requests>=2.0 in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from gym->gym-retro==0.6.1.dev52+g85e3de5) (2.20.1)
Requirement already satisfied: pyglet>=1.2.0 in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from gym->gym-retro==0.6.1.dev52+g85e3de5) (1.3.2)
Requirement already satisfied: six in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from gym->gym-retro==0.6.1.dev52+g85e3de5) (1.11.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-retro==0.6.1.dev52+g85e3de5) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-retro==0.6.1.dev52+g85e3de5) (1.24.1)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-retro==0.6.1.dev52+g85e3de5) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-retro==0.6.1.dev52+g85e3de5) (3.0.4)
Requirement already satisfied: future in c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages (from pyglet>=1.2.0->gym->gym-retro==0.6.1.dev52+g85e3de5) (0.17.1)
Installing collected packages: gym-retro
  Running setup.py develop for gym-retro
    Complete output from command "c:\users\seung ju\appdata\local\programs\python\python36\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\Seung Ju\\Desktop\\Programming\\Side_Projects\\AI\\sonic_env\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing gym_retro.egg-info\PKG-INFO
    writing dependency_links to gym_retro.egg-info\dependency_links.txt
    writing requirements to gym_retro.egg-info\requires.txt
    writing top-level names to gym_retro.egg-info\top_level.txt
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.a' found anywhere in distribution
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*-version' found under directory 'retro\cores'
    writing manifest file 'gym_retro.egg-info\SOURCES.txt'
    running build_ext
    -- Found PythonInterp: c:\users\seung ju\appdata\local\programs\python\python36\python.exe (found version "3.6.4")
    CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Seung Ju/Desktop/Programming/Side_Projects/AI/sonic_env/gym-retro/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Seung Ju\Desktop\Programming\Side_Projects\AI\sonic_env\gym-retro\setup.py", line 90, in <module>
        **kwargs
      File "c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\seung ju\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\seung ju\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\seung ju\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\develop.py", line 38, in run
        self.install_for_development()
      File "c:\users\seung ju\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\develop.py", line 138, in install_for_development
        self.run_command('build_ext')
      File "c:\users\seung ju\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\seung ju\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Seung Ju\Desktop\Programming\Side_Projects\AI\sonic_env\gym-retro\setup.py", line 53, in run
        subprocess.check_call([cmake_exe, '.', '-G', 'Unix Makefiles', build_type, pyext_suffix, pylib_dir, python_executable])
      File "c:\users\seung ju\appdata\local\programs\python\python36\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.exe', '.', '-G', 'Unix Makefiles', '', '-DPYEXT_SUFFIX:STRING=.cp36-win_amd64.pyd', '', '-DPYTHON_EXECUTABLE:STRING=c:\\users\\seung ju\\appdata\\local\\programs\\python\\python36\\python.exe']' returned non-zero exit status 1.

    ----------------------------------------
Command ""c:\users\seung ju\appdata\local\programs\python\python36\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\Seung Ju\\Desktop\\Programming\\Side_Projects\\AI\\sonic_env\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Users\Seung Ju\Desktop\Programming\Side_Projects\AI\sonic_env\gym-retro\
```

I have searched through internet to find similar symptoms and tried some methods like checking if gcc or g++ is installed, if CMake is downloaded and so on, however, i can`t seem to find the reason for myself.
I would appreciate to be adviced, Thanks in advance.

## System information

- [Operating system] Window 10, 64bits
- [Python version] 3.6.4
- [Gym Retro version] current version, downloaded yesterday
- gcc is installed, https://pastebin.com/Rn85DrUh

**Comment by christopherhesse** [comment]
Do you need to compile from source?  The binary is generally preferred for users.

Assuming you are compiling from source, did you follow the instructions carefully under https://github.com/openai/retro#windows-prerequisites ?

Assuming you did, it looks like https://github.com/msys2/msys2/wiki/Packages has a cmake package, can you uninstall your cmake and use that one instead?

Also why is your gcc under "C:\\Program Files\\Haskell Platform\\8.4.3"?

**Comment by seungjuchae** [comment]
I have followed the instruction on the page
https://github.com/openai/retro#windows-prerequisites

1. I downloaded (MSYS2)[http://www.msys2.org/] and ran the commands successfully
```pacman -Sy make mingw-w64-x86_64-gcc```

2. I previosuly had git installed, however, i redownloaded it and chose to use Git from the Windows Command Prompt

3. I ran the commands on cmd but nothing special happened(is this normal?)
```path %PATH%;C:\msys64\mingw64\bin;C:\msys64\usr\bin```
```set MSYSTEM=MINGW64```
![image](https://user-images.githubusercontent.com/33881908/52931958-90b8b300-334e-11e9-9e3f-a88c02256daf.png)

4. I have uninstalled the previous CMake and now the last thing i got to do is to download MYSY2 CMake package, which i assume is this one
https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-cmake
but how can i install it?


I also am not sure why gcc is under Haskell directory.. Maybe they are packaged together when being installed?
Thank you very much for helping me out.

**Comment by christopherhesse** [comment]
The build seems a bit hard to get working on windows.  If you're going to do it I'd suggest uninstalling all your existing gcc, cmake, etc and reinstalling the MSYS2 versions only.

What's the reason you need to build it from source?

**Comment by christopherhesse** [comment]
Closing due to lack of activity, building on windows should probably be tested though since it seems very hard to get right.
