### ISSUE TITLE
Installation error with pip3 install -e .

### ISSUE THREAD

**Issue by auscar92** [openai/retro#134]
I've followed the instructions for the installation, and this is what I get when I run the command.
C:\Users\ausca\gym-retro>pip3 install -e .
Obtaining file:///C:/Users/ausca/gym-retro
Collecting gym (from gym-retro==0.7.0.dev57+g71124f0)
  Using cached https://files.pythonhosted.org/packages/c7/98/fad8b85827d9aca922eec6a8747dd696aac281ebdc4b1225acf51f8f612f/gym-0.12.0.tar.gz
Collecting scipy (from gym->gym-retro==0.7.0.dev57+g71124f0)
  Using cached https://files.pythonhosted.org/packages/a9/b4/5598a706697d1e2929eaf7fe68898ef4bea76e4950b9efbe1ef396b8813a/scipy-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Could not locate executable g77
    Could not locate executable f77
    Could not locate executable ifort
    Could not locate executable ifl
    Could not locate executable f90
    /usr/bin/DF: /what: No such file or directory
    Could not locate executable efl
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable g95
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
    'svnversion' is not recognized as an internal or external command,
    operable program or batch file.
    non-existing path in 'numpy\\distutils': 'site.cfg'
    Running from numpy source directory.
    C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\setup.py:390: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\misc_util.py:476: SyntaxWarning: "is" with a literal. Did you mean "=="?
      return is_string(s) and ('*' in s or '?' is s)
    C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\system_info.py:638: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\system_info.py:638: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\system_info.py:638: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
    C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\system_info.py:638: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\system_info.py:638: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
        self.run_command("egg_info")
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\command\egg_info.py", line 26, in run
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\command\build_src.py", line 148, in run
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\command\build_src.py", line 159, in build_sources
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\command\build_src.py", line 292, in build_library_sources
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\command\build_src.py", line 375, in generate_sources
      File "numpy\core\setup.py", line 665, in get_mathlib_info
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\command\config.py", line 241, in try_link
        self._check_compiler()
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\command\config.py", line 52, in _check_compiler
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\_msvccompiler.py", line 239, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\setup.py", line 415, in <module>
        cmdclass = {'sdist': sdist_checked}
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\setup.py", line 407, in setup_package

      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\core.py", line 171, in setup
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\setup.py", line 415, in <module>
        cmdclass = {'sdist': sdist_checked}
      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\setup.py", line 407, in setup_package

      File "C:\Users\ausca\AppData\Local\Temp\easy_install-ov3kp1a6\numpy-1.16.2\numpy\distutils\core.py", line 171, in setup
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ausca\AppData\Local\Temp\pip-install-sa88ecin\scipy\setup.py", line 492, in <module>
        setup_package()
      File "C:\Users\ausca\AppData\Local\Temp\pip-install-sa88ecin\scipy\setup.py", line 488, in setup_package
        setup(**metadata)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 721, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\users\ausca\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ausca\AppData\Local\Temp\pip-install-sa88ecin\scipy\

I've tried installing scipy but that isn't working.  I updated the setuptools and tried everything I can to get it to work.
I appreciate the help!
## System information

- Windows 10
- 3.7.1
- 0.6.0

**Comment by christopherhesse** [comment]
Can I ask why you are installing from source?

**Comment by auscar92** [comment]
I tried after just running the normal installation to see if it would be different, but there were errors.  I tried again just now, and it gave what appears to be the same error.

**Comment by endrift** [comment]
This is an error compiling numpy, a dependency being pulled in, not gym-retro.
