### ISSUE TITLE
Unable to execute scripts/playback_movie.py

### ISSUE THREAD

**Issue by dnk8n** [openai/retro#14]
## Issue summary

When I execute the command below:
`python scripts/playback_movie.py SonicTheHedgehog-Genesis-GreenHillZone.Act1-0000.bk2`

I get the following output:
```
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, rawvideo, from 'pipe:5':
  Duration: N/A, start: 0.000000, bitrate: 103086 kb/s
    Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x224, 103086 kb/s, 59.92 tbr, 59.92 tbn, 59.92 tbc
Guessed Channel Layout for  Input Stream #1.0 : stereo
Input #1, s16le, from 'pipe:7':
  Duration: N/A, bitrate: 1411 kb/s
    Stream #1:0: Audio: pcm_s16le, 44100 Hz, 2 channels, s16, 1411 kb/s
[libx264 @ 0x215b360] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0x215b360] profile High, level 2.1
[libx264 @ 0x215b360] 264 - core 148 r2643 5c65704 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[aac @ 0x215c2a0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
Traceback (most recent call last):
  File "../retro/scripts/playback_movie.py", line 4, in <module>
    main()
  File "/.../openai-retro-contest/venv/lib/python3.6/site-packages/retro/scripts/playback_movie.py", line 114, in main
    playback_movie(emulator, m, monitor_csv, movie.replace('.bk2', '.mp4'), args.viewer, delay)
  File "/.../openai-retro-contest/venv/lib/python3.6/site-packages/retro/scripts/playback_movie.py", line 58, in playback_movie
    os.write(video, bytes(display))
  File "/.../openai-retro-contest/venv/lib/python3.6/site-packages/retro/scripts/playback_movie.py", line 40, in killprocs
    viewer_proc.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

I am unsure what further information is useful to debug this. Any help would be appreciated. I am happy to provide more information if necessary.

Thank you.

## System information

- Linux ... 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Python 3.6.2 (default, Jul 17 2017, 23:14:31) [GCC 5.4.0 20160609] on linux
- gym-retro==0.5.3 [gym_retro-0.5.3-cp36-cp36m-linux_x86_64.whl]

**Comment by praveen-palanisamy** [comment]
Seems like the [retro/retro/scripts/playback_movie.py](https://github.com/openai/retro/blob/1363ed6825ac836d3a7e57919ef0984a9ccc0ff6/retro/scripts/playback_movie.py) script is broken.

The `AttributeError: 'NoneType' object has no attribute 'terminate'` is coming from [this line](https://github.com/openai/retro/blob/1363ed6825ac836d3a7e57919ef0984a9ccc0ff6/retro/scripts/playback_movie.py#L40):
`viewer_proc.terminate()`

The `viewer_proc` does not exist because the `viewer` object is `None` and that is because the `--viewer` argument is not set when the `playback_movie.py`'s `main()` is called.

### Fix 1: I modified the `killprocs(...)` method like below:

```
def killprocs(*args, **kwargs):
    ffmpeg_proc.terminate()
    if viewer:
        viewer_proc.terminate()
    viewer_proc.wait()
    raise BrokenPipeError
```
There is also this error/warning: 
` [aac @ 0x215c2a0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.`

### Fix2: So I changed [line 27](https://github.com/openai/retro/blob/1363ed6825ac836d3a7e57919ef0984a9ccc0ff6/retro/scripts/playback_movie.py#L27) to this:
` ffmpeg_proc = subprocess.Popen(['ffmpeg', '-y', 'strict', '-2',`

The `playback_movie.py` script now runs fine but it does not seem to generate a valid `*.mp4` file. I haven't looked any deeper that that.

**Comment by endrift** [comment]
Please let me know if this is fixed.

**Comment by dnk8n** [comment]
@praveen-palanisamy @endrift  It's looking good. Video played back very well.

FYI, here is the log output:

```
python playback_movie.py ../../retro-contest/SonicTheHedgehog-Genesis-GreenHillZone.Act1-0000.bk2 
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, rawvideo, from 'pipe:5':
  Duration: N/A, start: 0.000000, bitrate: 103086 kb/s
    Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x224, 103086 kb/s, 59.92 tbr, 59.92 tbn, 59.92 tbc
Guessed Channel Layout for  Input Stream #1.0 : stereo
Input #1, s16le, from 'pipe:7':
  Duration: N/A, bitrate: 1411 kb/s
    Stream #1:0: Audio: pcm_s16le, 44100 Hz, 2 channels, s16, 1411 kb/s
[libx264 @ 0x1a70460] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 0x1a70460] profile High, level 2.1
[libx264 @ 0x1a70460] 264 - core 148 r2643 5c65704 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '../../retro-contest/SonicTheHedgehog-Genesis-GreenHillZone.Act1-0000.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 320x224, q=-1--1, 59.92 fps, 152024 tbn, 59.92 tbc
    Metadata:
      encoder         : Lavc56.60.100 libx264
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc56.60.100 aac
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
[s16le @ 0x1a645e0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 60)
frame=97123 fps=946 q=-1.0 Lsize=  266801kB time=00:27:00.82 bitrate=1348.5kbits/s    
video:238156kB audio:26167kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.937537%
[libx264 @ 0x1a70460] frame I:389   Avg QP:19.33  size: 39540
[libx264 @ 0x1a70460] frame P:53584 Avg QP:23.63  size:  3884
[libx264 @ 0x1a70460] frame B:43150 Avg QP:30.64  size:   472
[libx264 @ 0x1a70460] consecutive B-frames: 27.6% 34.1% 16.0% 22.3%
[libx264 @ 0x1a70460] mb I  I16..4:  4.5%  4.0% 91.5%
[libx264 @ 0x1a70460] mb P  I16..4:  0.2%  0.2%  0.5%  P16..4: 21.8%  7.3%  6.5%  0.0%  0.0%    skip:63.4%
[libx264 @ 0x1a70460] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  8.8%  3.2%  1.6%  direct: 4.0%  skip:82.4%  L0:40.5% L1:46.9% BI:12.6%
[libx264 @ 0x1a70460] 8x8 transform intra:13.0% inter:4.9%
[libx264 @ 0x1a70460] coded y,uvDC,uvAC intra: 66.9% 84.2% 81.9% inter: 9.1% 17.7% 16.6%
[libx264 @ 0x1a70460] i16 v,h,dc,p: 46% 35% 18%  0%
[libx264 @ 0x1a70460] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu:  9%  5% 79%  1%  1%  1%  1%  1%  2%
[libx264 @ 0x1a70460] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 16% 19%  6%  6%  7%  7%  7%  9%
[libx264 @ 0x1a70460] i8c dc,h,v,p: 50% 25% 18%  8%
[libx264 @ 0x1a70460] Weighted P-Frames: Y:0.1% UV:0.1%
[libx264 @ 0x1a70460] ref P L0: 78.2% 21.8%
[libx264 @ 0x1a70460] ref B L0: 92.9%  7.1%
[libx264 @ 0x1a70460] ref B L1: 97.8%  2.2%
[libx264 @ 0x1a70460] kb/s:1203.70

```
