### ISSUE TITLE
Integrating New States into an already existing game error

### ISSUE THREAD

**Issue by seravee121** [openai/retro#154]
## Issue summary

Hello, when I try to play `MegaMan-Nes` using new states with my algorithm made in the integration UI, I run into this error: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Josh's PC\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "F:\Games\PyCharmProjects\FinalYearProjectMegaman\lib\jerk.py", line 163, in run
    env = TrackedEnv(create_env(self.game, current_level))
  File "F:\Games\PyCharmProjects\FinalYearProjectMegaman\lib\env.py", line 14, in create_env
    env = MegamanDiscretizer(make(env_name, env_state))
Traceback (most recent call last):
  File "f:\games\pycharmprojects\venv\src\retro-contest-support\support\retro_contest\local.py", line 12, in make
    env = retro.make(game, state, scenario='contest', use_restricted_actions=use_restricted_actions)
  File "F:\Games\PyCharmProjects\venv\lib\site-packages\retro\__init__.py", line 55, in make
    return RetroEnv(game, state, inttype=inttype, **kwargs)
  File "F:\Games\PyCharmProjects\venv\lib\site-packages\retro\retro_env.py", line 60, in __init__
    self.load_state(self.statename, inttype)
  File "F:\Games\PyCharmProjects\venv\lib\site-packages\retro\retro_env.py", line 271, in load_state
    with gzip.open(retro.data.get_file_path(self.gamename, statename, inttype), 'rb') as fh:
  File "C:\Users\Josh's PC\AppData\Local\Programs\Python\Python37\lib\gzip.py", line 57, in open
    raise TypeError("filename must be a str or bytes object, or a file")
TypeError: filename must be a str or bytes object, or a file

But when I only include `Level1.state`  (the only state that Megaman has by default) this error does not occur.

Have I missed a step in integrating the new states?

## System information

- Windos 10
- 3.7.1
- Latest Version

**Comment by christopherhesse** [comment]
Could you try using the absolute path to your save state, e.g. "C:/Users/whatever/mymegamanstate.state"?

**Comment by christopherhesse** [comment]
Going to assume this is just a bad path to the save state, closing due to lack of activity.  Please file a new issue if this is still a problem.
