### ISSUE TITLE
Installation problem with gym-retro

### ISSUE THREAD

**Issue by Jarelk** [openai/retro#157]
## Issue summary

I've got an error I can't figure out. From what I've figured it's a problem with the installer trying to clone a git repo in a non-repo directory, but I do not understand where it is trying that in the first place. I'm running the `pip3 install gym-retro` command inside a virtual environment using the `virtualenv` package. 

```
    running build_ext
    -- Submodules seem to be missing. Attempting to clone now.
    fatal: not a git repository (or any of the parent directories): .git
    CMake Error at CMakeLists.txt:13 (message):
      Failed to check out submodules.  Aborting.


    -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Jaimy\AppData\Local\Temp\pip-install-gi9sj92w\gym-retro\setup.py", line 92, in <module>
        **kwargs
      File "e:\informatica\python\openai\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "e:\informatica\python\openai\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Jaimy\AppData\Local\Temp\pip-install-gi9sj92w\gym-retro\setup.py", line 53, in run
        subprocess.check_call([cmake_exe, '.', '-G', 'Unix Makefiles', build_type, pyext_suffix, pylib_dir, python_executable])
      File "c:\users\jaimy\appdata\local\programs\python\python37-32\Lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['E:\\Informatica\\Python\\OpenAI\\Scripts\\cmake.exe', '.', '-G', 'Unix Makefiles', '', '-DPYEXT_SUFFIX:STRING=.cp37-win32.pyd', '-DPYLIB_DIRECTORY:PATH=build\\lib.win32-3.7', '-DPYTHON_EXECUTABLE:STRING=e:\\informatica\\python\\openai\\scripts\\python.exe']' returned non-zero exit status 1.
```

## System information

- Windows 10
- Python version 3.7.3
- Cmake version 3.13.3
- Gym-Retro: Latest?

**Comment by christopherhesse** [comment]
You're attempting to install the binary wheel package from pypi right?

**Comment by Jarelk** [comment]
> You're attempting to install the binary wheel package from pypi right?

Yes, it seems that's where its failing.

**Comment by Jarelk** [comment]
Oops I closed it.

**Comment by christopherhesse** [comment]
It looks a lot like it's building from source instead of installing the wheel but I'm not sure why that would happen.  What happens if you run `pip install https://files.pythonhosted.org/packages/32/80/858535727a8d6b5058a1ef1f6f4c803af7ec154fe074f91f08ab5e96890c/gym_retro-0.7.0-cp37-cp37m-win_amd64.whl`?

**Comment by Jarelk** [comment]
> It looks a lot like it's building from source instead of installing the wheel but I'm not sure why that would happen. What happens if you run `pip install https://files.pythonhosted.org/packages/32/80/858535727a8d6b5058a1ef1f6f4c803af7ec154fe074f91f08ab5e96890c/gym_retro-0.7.0-cp37-cp37m-win_amd64.whl`?

I get the message `gym_retro-0.7.0-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.`

**Comment by christopherhesse** [comment]
Seems like you're either not using windows, not using python 3.7, or not using a 64 bit operating system, can you check all of those?

**Comment by Jarelk** [comment]
> Seems like you're either not using windows, not using python 3.7, or not using a 64 bit operating system/version of python, can you check all of those?

I am definitely using Windows 10, and am definitely running on a 64 bit PC. Built this thing myself. The python version used in the virtual environment is 3.7.3. There MIGHT be a problem with the whole schtick with `pip` being different from `pip3`, because I notice that python 2.7 is also installed on my PC. I don't really get how that works.

**Comment by Jarelk** [comment]
It worked! My solution was to remove every version of Python, install ONLY the 64-bit newest version, reinstall virtualenv, rebuild the virtual environment, and install gym-retro in there. Seems it was an issue with my version of python after all. I am still confused about why the warning is talking about .git.

Thanks for the help, I managed to find it thanks to you. Working with installing the right packages or libraries and correctly doing paths is something I am still learning. Such a hassle sometimes.

**Comment by christopherhesse** [comment]
It's falling back to building from source.  I put the source on pypi thinking it would be useful but it may only cause issues and should probably be removed.

**Comment by ChrisYanY** [comment]
嗯，还是得跟着lin大在conda里瞎搞才可以
