### ISSUE TITLE
Import retro: invalid syntax

### ISSUE THREAD

**Issue by danschmid** [openai/retro#158]
I am attempting to install gym-retro and import some ROMs, but when i try to import retro in my python file it throws an error: 

Traceback (most recent call last):
  File "galaga.py", line 1, in <module>
    import retro
  File "/home/user/Desktop/retro-gym/gym-retro/retro/__init__.py", line 2, in <module>
    import retro.data
  File "/home/user/Desktop/retro-gym/gym-retro/retro/data/__init__.py", line 388
    def merge(*args, quiet=True):
                         ^
SyntaxError: invalid syntax

While building, i also had an error when I typed "pip3 install -e.":

 Rolling back uninstall of gym-retro
Command "/home/user/Desktop/retro-gym/bin/python -c "import setuptools, tokenize;__file__='/home/user/Desktop/retro-gym/gym-retro/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/user/Desktop/retro-gym/gym-retro/

I made sure to install cmake before running this, and though some other threads reported similar errors, none of those fixes seemed to work for me.

## System information

- Ubuntu 16.04.5
- Python 3.6.5
- gym-retro 0.5.3

**Comment by danschmid** [comment]
Nevermind, found out it was because i wasn't executing the code from my virtual environment.
