### ISSUE TITLE
I was trying to integrate a new NES Rom and although it imports when i run make it shows that the rom doesn't exist

### ISSUE THREAD

**Issue by nikhilfeb95** [openai/retro#181]
Is it the problem with the rom? I integrated it using the Integration UI. 

 python -m retro.import .
Importing StreetFighter-Nes
Imported 1 games
nikhil@nikhil-Lenovo-Y50-70:~/anaconda3/gym-retro/retro/data/contrib/StreetFighter-Nes$ python NeuralFighter.py 
Traceback (most recent call last):
  File "NeuralFighter.py", line 8, in <module>
    env = retro.make('StreetFighter-Nes', 'Guile.Act1')
  File "/home/nikhil/anaconda3/gym-retro/retro/__init__.py", line 49, in make
    retro.data.get_romfile_path(game, inttype)
  File "/home/nikhil/anaconda3/gym-retro/retro/data/__init__.py", line 288, in get_romfile_path
    raise FileNotFoundError("No romfiles found for game: %s" % game)
FileNotFoundError: No romfiles found for game: StreetFighter-Nes

**Comment by nikhilfeb95** [comment]
Moved it to the stable folder
