### ISSUE TITLE
Error installing retro package from source

### ISSUE THREAD

**Issue by faraazn** [openai/retro#208]
## Issue summary

Here's my original output when trying to build from source:

```
running build
running build_py
copying retro/VERSION.txt -> build/lib.linux-ppc64le-3.6/retro
running build_ext
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/faraaz/workspace/retro
[  0%] Generating build/lib.linux-ppc64le-3.6/retro/cores/stella_libretro.so
[  0%] Generating build/lib.linux-ppc64le-3.6/retro/cores/gambatte_libretro.so
[  0%] Built target gba
[ 12%] Built target genesis
[ 12%] Generating build/lib.linux-ppc64le-3.6/retro/cores/snes9x_libretro.so
[ 12%] Generating build/lib.linux-ppc64le-3.6/retro/cores/mednafen_pce_fast_libretro.so
[ 12%] Built target nes
[ 83%] Built target zip
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[4]: *** [gambatte_libretro.so] Error 1
make[3]: *** [build/lib.linux-ppc64le-3.6/retro/cores/gambatte_libretro.so] Error 2
make[2]: *** [CMakeFiles/gb.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[4]: *** [snes9x_libretro.so] Error 1
make[3]: *** [build/lib.linux-ppc64le-3.6/retro/cores/snes9x_libretro.so] Error 2
make[2]: *** [CMakeFiles/snes.dir/all] Error 2
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[4]: *** [mednafen_pce_fast_libretro.so] Error 1
make[3]: *** [build/lib.linux-ppc64le-3.6/retro/cores/mednafen_pce_fast_libretro.so] Error 2
make[2]: *** [CMakeFiles/pce.dir/all] Error 2
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[4]: *** [stella_libretro.so] Error 1
make[3]: *** [build/lib.linux-ppc64le-3.6/retro/cores/stella_libretro.so] Error 2
make[2]: *** [CMakeFiles/atari2600.dir/all] Error 2
make[1]: *** [CMakeFiles/retro.dir/rule] Error 2
make: *** [retro] Error 2
Traceback (most recent call last):
  File "setup.py", line 96, in <module>
    **kwargs
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 64, in run
    subprocess.check_call([make_exe, jobs, 'retro'])
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/make', '-j160', 'retro']' returned non-zero exit status 2.
```

This is my original output from running gcc -v

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64le-redhat-linux/4.8.5/lto-wrapper
Target: ppc64le-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/cloog-install --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --enable-targets=powerpcle-linux --disable-multilib --with-cpu-64=power8 --with-tune-64=power8 --build=ppc64le-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
```

And my original output from running g++ -v

```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64le-redhat-linux/4.8.5/lto-wrapper
Target: ppc64le-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/cloog-install --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --enable-targets=powerpcle-linux --disable-multilib --with-cpu-64=power8 --with-tune-64=power8 --build=ppc64le-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
```

Following issue #65  I tried running the command `cmake . -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)` but that did not fix the issue. Then I tried updating my gcc version with spack, and got this new version info:

```
Reading specs from /home/software/spack/gcc/8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz/lib/gcc/powerpc64le-unknown-linux-gnu/8.3.0/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/software/spack/gcc/8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz/libexec/gcc/powerpc64le-unknown-linux-gnu/8.3.0/lto-wrapper
Target: powerpc64le-unknown-linux-gnu
Configured with: /tmp/s_b/spack-stage/spack-stage-gcc-8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz/spack-src/configure --prefix=/home/software/spack/gcc/8.3.0-xdjkb2mmftikxvoeeyaxtxcjtpltcgiz --with-pkgversion='Spack GCC' --with-bugurl=https://github.com/spack/spack/issues --disable-multilib --enable-languages=c,c++,fortran --disable-nls --with-libiconv-prefix=/home/software/spack/libiconv/1.16-xaq2kxrcomr3vckatmsuqhyoxjvtouy6 --with-mpfr=/home/software/spack/mpfr/3.1.6-vwusntzsgcrzwr5xkxryutamzku3gd32 --with-gmp=/home/software/spack/gmp/6.1.2-koxo72p6rwierbq226y6bll6aqemfkyk --with-system-zlib --with-mpc=/home/software/spack/mpc/1.1.0-qazfwlzzf4votp56yd2oav5kuxk55u2e --with-isl=/home/software/spack/isl/0.18-w6ssv2xjon5ciehqltsn2ers3w6xbdd5
Thread model: posix
gcc version 8.3.0 (Spack GCC) 
```

And now I'm getting a new error:

```

running build
running build_py
copying retro/VERSION.txt -> build/lib.linux-ppc64le-3.6/retro
running build_ext
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/faraaz/workspace/retro
[  0%] Built target atari2600
[  4%] Built target genesis
[  4%] Built target gba
[  8%] Built target nes
[ 12%] Built target snes
[ 12%] Built target pce
[ 16%] Built target gb
[ 87%] Built target zip
[ 87%] Generating third-party/luajit/src/libluajit.a
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^~~~~
make[4]: *** No rule to make target `vm_ppc64.dasc', needed by `host/buildvm_arch.h'.  Stop.
make[3]: *** [third-party/luajit/src/libluajit.a] Error 2
make[2]: *** [CMakeFiles/retro-base.dir/all] Error 2
make[1]: *** [CMakeFiles/retro.dir/rule] Error 2
make: *** [retro] Error 2
Traceback (most recent call last):
  File "setup.py", line 96, in <module>
    **kwargs
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 64, in run
    subprocess.check_call([make_exe, jobs, 'retro'])
  File "/nobackup/users/faraaz/anaconda3/envs/py3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/make', '-j160', 'retro']' returned non-zero exit status 2.
```

From what I can tell from the info below, this has to do with my machine architecture? I don't know how to fix this so help would be appreciated :/

## System information
- `lsb_release -a`:
```
LSB Version:	:core-4.1-noarch:core-4.1-ppc64le:cxx-4.1-noarch:cxx-4.1-ppc64le:desktop-4.1-noarch:desktop-4.1-ppc64le:languages-4.1-noarch:languages-4.1-ppc64le:printing-4.1-noarch:printing-4.1-ppc64le
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.6 (Maipo)
Release:	7.6
Codename:	Maipo
```
- Python 3.6.10
- gym-retro-0.7.1

**Comment by christopherhesse** [comment]
This does indeed appear to be an error that luajit does not support PowerPC.  Could you try a non-PowerPC computer?  I think we may need to list the supported CPU architectures in the README if people are often confused by this.

It may be possible to compile retro without luajit, but I'm not certain how hard that would be, or if all the cores support PPC.

**Comment by faraazn** [comment]
So I found this repository which is a LuaJIT port to PPC64: https://github.com/PPC64/LuaJIT

I replaced the `retro/third-party/luajit` folder with this repository, and that fixed my issue. Thanks!

**Comment by endrift** [comment]
You may encounter problems with some of the emulators used. Not all of them are tested on much other than x64.

**Comment by faraazn** [comment]
Thanks for the heads up - it seems to be working normally with the emulator I'm using, SonicTheHedgehog-Genesis.
