### ISSUE TITLE
Roms not found for custom integrations.

### ISSUE THREAD

**Issue by somersaultjump** [openai/retro#218]
I have followed the documents posted [here](https://retro.readthedocs.io/en/latest/integration.html) to add a custom rom integration.

I'm using the USA rom from the recommended no intro collection.

```
Traceback (most recent call last):
  File "trainModel.py", line 42, in <module>
    main()
  File "trainModel.py", line 31, in main
    env = retro.make(game='Contra-Nes', use_restricted_actions=retro.Actions.DISCRETE)
  File "/Users/daniel/.pyenv/versions/3.6.5/lib/python3.6/site-packages/retro/__init__.py", line 49, in make
    retro.data.get_romfile_path(game, inttype)
  File "/Users/daniel/.pyenv/versions/3.6.5/lib/python3.6/site-packages/retro/data/__init__.py", line 288, in get_romfile_path
    raise FileNotFoundError("No romfiles found for game: %s" % game)
FileNotFoundError: No romfiles found for game: Contra-Nes
```

Archive manifest:
customIntegration.py
data.json
level1.state
metadata.json
rom.sha (used shamus on macOS to get this.  I have a sneaking suspicion this is the issue.)
scenario.json
trainModel.py

[Archive.zip](https://github.com/openai/retro/files/5468075/Archive.zip)

## System information

- MacOS 10.15.7 / Ubuntu 20.04
- 3.6.5 / 3.7
- 0.8.0

**Comment by christopher-hesse** [comment]
Can you call it something besides `Contra-Nes` and try again? It may be conflicting with this existing experimental integration: https://github.com/openai/retro/tree/master/retro/data/experimental/Contra-Nes

**Comment by christopherhesse** [comment]
Closing due to lack of activity.
