### ISSUE TITLE
Ubuntu 16.04 Installation issues

### ISSUE THREAD

**Issue by ConorYatesKoch** [openai/retro#22]
## Issue summary

``sudo pip install -e .`` does not work. I get the following output and error message:
```
Obtaining file:///home/shinobu/Documents/School/gym-retro
Requirement already satisfied: gym in /usr/local/lib/python2.7/dist-packages (from gym-retro==0.5.4.dev7+g5073b40)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from gym->gym-retro==0.5.4.dev7+g5073b40)
Requirement already satisfied: numpy>=1.10.4 in /usr/lib/python2.7/dist-packages (from gym->gym-retro==0.5.4.dev7+g5073b40)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from gym->gym-retro==0.5.4.dev7+g5073b40)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python2.7/dist-packages (from gym->gym-retro==0.5.4.dev7+g5073b40)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from pyglet>=1.2.0->gym->gym-retro==0.5.4.dev7+g5073b40)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0->gym->gym-retro==0.5.4.dev7+g5073b40)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0->gym->gym-retro==0.5.4.dev7+g5073b40)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0->gym->gym-retro==0.5.4.dev7+g5073b40)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0->gym->gym-retro==0.5.4.dev7+g5073b40)
Installing collected packages: gym-retro
  Running setup.py develop for gym-retro
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/home/shinobu/Documents/School/gym-retro/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing requirements to gym_retro.egg-info/requires.txt
    writing gym_retro.egg-info/PKG-INFO
    writing top-level names to gym_retro.egg-info/top_level.txt
    writing dependency_links to gym_retro.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    package init file 'data/__init__.py' not found (or not a regular file)
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.a' found anywhere in distribution
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*-version' found under directory 'retro/cores'
    writing manifest file 'gym_retro.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/shinobu/Documents/School/gym-retro/setup.py", line 67, in <module>
        use_scm_version=use_scm_version
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/develop.py", line 119, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/shinobu/Documents/School/gym-retro/setup.py", line 33, in run
        suffix = super(CMakeBuild, self).get_ext_filename('')
    TypeError: super() argument 1 must be type, not classobj

--------------------------

Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/home/shinobu/Documents/School/gym-retro/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/shinobu/Documents/School/gym-retro/
```
I do have glibc installed (libc6 on Ubuntu), version 2.23. I do have CMake installed, version 3.11.0.

## System information

- Ubuntu 16.04
- Python 3.5.2
- commit 5073b40

**Comment by endrift** [comment]
Use `pip3` instead of `pip`, this is using Python 2. Same as #1.

**Comment by 921kiyo** [comment]
Hi, 

I followed the documentation and used pip3 to install, but I am getting the error "FileNotFoundError: Game not found: SonicTheHedgehog-Genesis. Did you make sure to import the ROM?" I cannot seem to find the instruction about this in the documentation. I am running it on Ubuntu 16.04.
