### ISSUE TITLE
Installation fails on Mac M1

### ISSUE THREAD

**Issue by Ryan-Rudes** [openai/retro#231]
## Issue summary

The installation fails when using Python 3.8 on Mac M1 (and presumably all Apple Silicon hardware)

## System information

- macOS Big Sur 11.2.2
- Python 3.8.8
- Mac M1

This failure occurs when during the installation using `pip install gym` when the wheel is being built:

The error is over 600 pages long in normal font size, so I'll provide the beginning and the end:

```
(base)  ryanrudes@Ryans-Mac-mini  ~  pip install gym-retro
Collecting gym-retro
  Using cached gym-retro-0.7.1.tar.gz (168.7 MB)
Requirement already satisfied: gym in /opt/homebrew/Caskroom/miniforge/base/lib/python3.8/site-packages (from gym-retro) (0.18.0)
Requirement already satisfied: pyglet==1.*,>=1.3.2 in ./.local/lib/python3.8/site-packages (from gym-retro) (1.5.15)
Requirement already satisfied: numpy>=1.10.4 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.8/site-packages (from gym->gym-retro) (1.20.1)
Requirement already satisfied: cloudpickle<1.7.0,>=1.2.0 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.8/site-packages (from gym->gym-retro) (1.6.0)
Requirement already satisfied: Pillow<=7.2.0 in /opt/homebrew/Caskroom/miniforge/base/lib/python3.8/site-packages (from gym->gym-retro) (7.2.0)
Requirement already satisfied: scipy in /opt/homebrew/Caskroom/miniforge/base/lib/python3.8/site-packages (from gym->gym-retro) (1.6.0)
Building wheels for collected packages: gym-retro
  Building wheel for gym-retro (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/Caskroom/miniforge/base/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-install-hd44tqgm/gym-retro/setup.py'"'"'; __file__='"'"'/private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-install-hd44tqgm/gym-retro/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-wheel-740ve2hy
       cwd: /private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-install-hd44tqgm/gym-retro/
  Complete output (7634 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11.0-arm64-3.8
  creating build/lib.macosx-11.0-arm64-3.8/retro
  copying retro/enums.py -> build/lib.macosx-11.0-arm64-3.8/retro
  copying retro/__init__.py -> build/lib.macosx-11.0-arm64-3.8/retro
  copying retro/retro_env.py -> build/lib.macosx-11.0-arm64-3.8/retro
  creating build/lib.macosx-11.0-arm64-3.8/retro/data
  copying retro/data/__init__.py -> build/lib.macosx-11.0-arm64-3.8/retro/data
```

...

```
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/contest.json -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/rom.delta -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/StarLightZone.Custom.state -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/metadata.json -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/SpringYardZone.Custom.state -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/data.json -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/script.lua -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/GreenHillZone.Custom.state -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/scenario.json -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    copying retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis/rom.sha -> build/lib.macosx-11.0-arm64-3.8/retro/data/contrib/SonicTheHedgehogCustomLeaderboard-Genesis
    running build_ext
    CMake Deprecation Warning at third-party/gtest/googlemock/CMakeLists.txt:46 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.

      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.


    CMake Deprecation Warning at third-party/gtest/googletest/CMakeLists.txt:53 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.

      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.


    -- Configuring done
    -- Generating done
    -- Build files have been written to: /private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-install-hd44tqgm/gym-retro
    [  0%] Generating build/lib.macosx-11.0-arm64-3.8/retro/cores/gambatte_libretro.dylib
    [  0%] Generating build/lib.macosx-11.0-arm64-3.8/retro/cores/genesis_plus_gx_libretro.dylib
    [  0%] Generating build/lib.macosx-11.0-arm64-3.8/retro/cores/fceumm_libretro.dylib
    [  4%] Generating build/lib.macosx-11.0-arm64-3.8/retro/cores/snes9x_libretro.dylib
    [  4%] Generating build/lib.macosx-11.0-arm64-3.8/retro/cores/stella_libretro.dylib
    [  4%] Generating build/lib.macosx-11.0-arm64-3.8/retro/cores/mgba_libretro.dylib
    [  4%] Generating build/lib.macosx-11.0-arm64-3.8/retro/cores/mednafen_pce_fast_libretro.dylib
    [ 75%] Built target zip
    In file included from libgambatte/src/bootloader.cpp:2:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:60:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    fatal: not a git repository (or any of the parent directories): .git
    fatal: not a git repository (or any of the parent directories): .git
    In file included from libgambatte/src/cpu.cpp:19:
    In file included from libgambatte/src/cpu.h:22:
    In file included from libgambatte/src/../include/gambatte.h:27:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:504:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string_view:175:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__string:57:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:641:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:60:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    fatal: not a git repository (or any of the parent directories): .git
    fatal: not a git repository (or any of the parent directories): .git
    fatal: not a git repository (or any of the parent directories): .git
    fatal: not a git repository (or any of the parent directories): .git
    core/cd_hw/libchdr/src/bitstream.c:13:10: fatal error: 'stdlib.h' file not found
    #include <stdlib.h>
             ^~~~~~~~~~
    1 error generated.
    In file included from ../apu/apu.cpp:190:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/math.h:301:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
    #include_next <stdlib.h>
                  ^~~~~~~~~~
    In file included from src/arm/arm.c:6:
    In file included from ./include/mgba/internal/arm/arm.h:9:
    ./include/mgba-util/common.h:19:10: fatal error: 'ctype.h' file not found
    #include <ctype.h>
             ^~~~~~~~~
    make[4]: *** [core/cd_hw/libchdr/src/bitstream.o] Error 1
    make[3]: *** [build/lib.macosx-11.0-arm64-3.8/retro/cores/genesis_plus_gx_libretro.dylib] Error 2
    make[2]: *** [CMakeFiles/genesis.dir/all] Error 2
    make[2]: *** Waiting for unfinished jobs....
    In file included from src/boards/01-222.c:36:
    In file included from src/boards/mapinc.h:3:
    In file included from src/boards/../fceu.h:71:
    src/driver.h:4:10:In file included from stella/src/common/Base.cxx:20:
    In file included from stella/src/common/Base.hxx:23:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:37:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:214:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:95:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/wchar.h:118:15: fatal error: 'wchar.h' file not found
    #include_next <wchar.h>
                  ^~~~~~~~~
     fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^~~~~~~~~
    1 error generated.
    In file included from mednafen/pce_fast/huc6280.cpp:18:
    In file included from mednafen/pce_fast/pce.h:4:
    mednafen/pce_fast/../mednafen-types.h:4:10: fatal error: 'assert.h' file not found
    #include <assert.h>
             ^~~~~~~~~~
    1 error generated.
    make[4]: *** [src/arm/arm.o] Error 1
    make[4]: *** [src/boards/01-222.o] Error 1
    make[3]: *** [build/lib.macosx-11.0-arm64-3.8/retro/cores/mgba_libretro.dylib] Error 2
    make[2]: *** [CMakeFiles/gba.dir/all] Error 2
    make[3]: *** [build/lib.macosx-11.0-arm64-3.8/retro/cores/fceumm_libretro.dylib] Error 2
    make[2]: *** [CMakeFiles/nes.dir/all] Error 2
    In file included from libgambatte/src/gambatte.cpp:19:
    In file included from libgambatte/src/../include/gambatte.h:27:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:504:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string_view:175:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__string:57:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:641:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:60:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    In file included from stella/src/common/SoundSDL.cxx:22:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/sstream:173:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:138:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:214:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:95:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/wchar.h:118:15: fatal error: 'wchar.h' file not found
    #include_next <wchar.h>
                  ^~~~~~~~~
    1 error generated.
    make[4]: *** [libgambatte/src/bootloader.o] Error 1
    make[4]: *** Waiting for unfinished jobs....
    In file included from mednafen/pce_fast/input.cpp:18:
    In file included from mednafen/pce_fast/pce.h:4:
    mednafen/pce_fast/../mednafen-types.h:4:10: fatal error: 'assert.h' file not found
    #include <assert.h>
             ^~~~~~~~~~
    In file included from mednafen/pce_fast/pcecd.cpp:26:
    In file included from mednafen/pce_fast/../mednafen.h:4:
    ./mednafen/mednafen-types.h:4:10: fatal error: 'assert.h' file not found
    #include <assert.h>
             ^~~~~~~~~~
    1 error generated.
    make[4]: *** [libgambatte/src/cpu.o] Error 1
    1 error generated.
    make[4]: *** [../apu/apu.o] Error 1
    make[4]: *** Waiting for unfinished jobs....
    In file included from ../apu/bapu/dsp/sdsp.cpp:1:
    In file included from ../apu/bapu/snes/snes.hpp:4:
    In file included from ../snes9x.h:195:
    In file included from ../port.h:191:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdio.h:107:15: fatal error: 'stdio.h' file not found
    #include_next <stdio.h>
                  ^~~~~~~~~
    In file included from stella/src/emucore/AtariVox.cxx:20:
    In file included from stella/src/emucore/MT24LC256.hxx:26:
    In file included from stella/src/common/bspf.hxx:64:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:641:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:60:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    1 error generated.
    make[4]: *** [stella/src/common/Base.o] Error 1
    make[4]: *** Waiting for unfinished jobs....
    1 error generated.
    make[4]: *** [mednafen/pce_fast/huc6280.o] Error 1
    make[4]: *** Waiting for unfinished jobs....
    In file included from mednafen/pce_fast/pcecd_drive.cpp:18:
    In file included from mednafen/pce_fast/../mednafen.h:4:
    ./mednafen/mednafen-types.h:4:10: fatal error: 'assert.h' file not found
    #include <assert.h>
             ^~~~~~~~~~
    1 error generated.
    make[4]: *** [mednafen/pce_fast/input.o] Error 1
    1 error generated.
    1 error generated.
    make[4]: *** [libgambatte/src/gambatte.o] Error 1
    make[4]: *** [mednafen/pce_fast/pcecd.o] Error 1
    make[3]: *** [build/lib.macosx-11.0-arm64-3.8/retro/cores/gambatte_libretro.dylib] Error 2
    make[2]: *** [CMakeFiles/gb.dir/all] Error 2
    1 error generated.
    make[4]: *** [stella/src/common/SoundSDL.o] Error 1
    1 error generated.
    make[4]: *** [../apu/bapu/dsp/sdsp.o] Error 1
    make[3]: *** [build/lib.macosx-11.0-arm64-3.8/retro/cores/snes9x_libretro.dylib] Error 2
    make[2]: *** [CMakeFiles/snes.dir/all] Error 2
    1 error generated.
    make[4]: *** [stella/src/emucore/AtariVox.o] Error 1
    make[3]: *** [build/lib.macosx-11.0-arm64-3.8/retro/cores/stella_libretro.dylib] Error 2
    make[2]: *** [CMakeFiles/atari2600.dir/all] Error 2
    1 error generated.
    make[4]: *** [mednafen/pce_fast/pcecd_drive.o] Error 1
    make[3]: *** [build/lib.macosx-11.0-arm64-3.8/retro/cores/mednafen_pce_fast_libretro.dylib] Error 2
    make[2]: *** [CMakeFiles/pce.dir/all] Error 2
    make[1]: *** [CMakeFiles/retro.dir/rule] Error 2
    make: *** [retro] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-install-hd44tqgm/gym-retro/setup.py", line 71, in <module>
        setup(
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-install-hd44tqgm/gym-retro/setup.py", line 61, in run
        subprocess.check_call([make_exe, jobs, 'retro'])
      File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/make', '-j8', 'retro']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/homebrew/Caskroom/miniforge/base/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-install-hd44tqgm/gym-retro/setup.py'"'"'; __file__='"'"'/private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-install-hd44tqgm/gym-retro/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/v8/xbqyyrhx7mxd_dcm9x9jf8tc0000gn/T/pip-record-35_2n8gw/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/Caskroom/miniforge/base/include/python3.8/gym-retro Check the logs for full command output.
```

**Comment by mwidjaja1** [comment]
So I wasn't doing this on an Apple Silicon Mac but for what it's worth, I got the same issues you did. Here's how I got closer to the right answer (though not fully there yet) so at least I can find these files.

1. I installed Command Line tools via `xcode-select --install`
2. I was curious what C++ SDKs I was using so I ran `gcc -Wp,-v -E -`. It returned me a list of paths but `MacOSX10.14.sdk` appeared before `MacOSX10.15.sdk` which isn't ideal for Catalina (my OS). That didn't sound right so I did the next three steps.
3. In the terminal, I went to the CommandLineTools' SDK directory via `cd /Library/Developer/CommandLineTools/SDKs` 
4. I moved `MacOSX10.14.sdk` out by running `sudo mv MacOSX10.14.sdk ..` so I can bring it back in if I needed it.
5. I ran `gcc -Wp,-v -E -` again, noting that 10.15 is now higher up the list.
6. So I ran `make clean` and `make -j$(sysctl hw.ncpu | cut -d: -f2)` to build `gym-retro` again and... got further but not fully there yet.

**Comment by Takage** [comment]
having the same problem :(

**Comment by minghuayao81** [comment]
same issue here too... anyone got this issue fixed?

**Comment by FLSP** [comment]
Same. So frustrated

**Comment by MatPoliquin** [comment]
You can use a maintained fork called stable-retro, it supports M1:
[https://github.com/Farama-Foundation/stable-retro](https://github.com/Farama-Foundation/stable-retro)
