### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by deadpahn** [openai/retro#24]
## Issue summary
I'm getting this error trying to run the simple-agent example:

`~/Code/openai $ python3 simple-agent.py 
connecting to remote environment
Traceback (most recent call last):
  File "simple-agent.py", line 21, in <module>
    main()
  File "simple-agent.py", line 7, in main
    env = grc.RemoteEnv('tmp/sock')
  File "~/Code/openai/retro-contest/support/gym_remote/client.py", line 9, in init
    self.bridge.connect()
  File "~/Code/openai/retro-contest/support/gym_remote/bridge.py", line 251, in connect
    self.sock.connect(sock_path)
FileNotFoundError: [Errno 2] No such file or directory`

## System information

- Linux Mint
- Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux

**Comment by endrift** [comment]
Not a bug. That script (which is not part of this repository...) cannot run in isolation. It requires the remote.
