### ISSUE TITLE
AssertionError: Can't parse version f347d7e when trying to install

### ISSUE THREAD

**Issue by misterpilou** [openai/retro#254]
## Issue summary

pip3 install -e . Resulting in AssertionError: Can't parse version f347d7e

## System information

- Arch Linux
- Python 3.7.11
- Up to Date

```
    ERROR: Command errored out with exit status 1:
     command: /home/becaree/.local/share/virtualenvs/retro-bMGbzfbw/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/retro/roms/retro/setup.py'"'"'; __file__='"'"'/opt/retro/roms/retro/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ruj3j2zo
         cwd: /opt/retro/roms/retro/
    Complete output (35 lines):
    /opt/retro/roms/retro/.eggs/setuptools_scm-6.3.2-py3.7.egg/setuptools_scm/version.py:62: UserWarning: tag 'f347d7e' no version found
      warnings.warn(f"tag {tag!r} no version found")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/retro/roms/retro/setup.py", line 96, in <module>
        **kwargs
      File "/home/becaree/.local/share/virtualenvs/retro-bMGbzfbw/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/becaree/.pyenv/versions/3.7.11/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/becaree/.local/share/virtualenvs/retro-bMGbzfbw/lib/python3.7/site-packages/setuptools/dist.py", line 456, in __init__
        k: v for k, v in attrs.items()
      File "/home/becaree/.pyenv/versions/3.7.11/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/becaree/.local/share/virtualenvs/retro-bMGbzfbw/lib/python3.7/site-packages/setuptools/dist.py", line 807, in finalize_options
        ep(self)
      File "/home/becaree/.local/share/virtualenvs/retro-bMGbzfbw/lib/python3.7/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/opt/retro/roms/retro/.eggs/setuptools_scm-6.3.2-py3.7.egg/setuptools_scm/integration.py", line 65, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/opt/retro/roms/retro/.eggs/setuptools_scm-6.3.2-py3.7.egg/setuptools_scm/__init__.py", line 177, in _get_version
        parsed_version = _do_parse(config)
      File "/opt/retro/roms/retro/.eggs/setuptools_scm-6.3.2-py3.7.egg/setuptools_scm/__init__.py", line 128, in _do_parse
        version = _version_from_entrypoints(config) or _version_from_entrypoints(
      File "/opt/retro/roms/retro/.eggs/setuptools_scm-6.3.2-py3.7.egg/setuptools_scm/__init__.py", line 69, in _version_from_entrypoints
        version = _call_entrypoint_fn(root, config, ep.load())
      File "/opt/retro/roms/retro/.eggs/setuptools_scm-6.3.2-py3.7.egg/setuptools_scm/__init__.py", line 48, in _call_entrypoint_fn
        return fn(root, config=config)
      File "/opt/retro/roms/retro/.eggs/setuptools_scm-6.3.2-py3.7.egg/setuptools_scm/git.py", line 136, in parse
        config, wd, describe_command=describe_command, pre_parse=pre_parse
      File "/opt/retro/roms/retro/.eggs/setuptools_scm-6.3.2-py3.7.egg/setuptools_scm/git.py", line 177, in _git_parse_inner
        config=config,
      File "/opt/retro/roms/retro/.eggs/setuptools_scm-6.3.2-py3.7.egg/setuptools_scm/version.py", line 188, in meta
        assert parsed_version is not None, "Can't parse version %s" % tag
    AssertionError: Can't parse version f347d7e
    ----------------------------------------
WARNING: Discarding file:///opt/retro/roms/retro. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by WesPereira** [comment]
Same issue on arch 5.14.12, python 3.8.10

**Comment by nicoxxl** [comment]
Same problem on my [PR](https://github.com/openai/retro/pull/236)

**Comment by aram-azbekian** [comment]
Will there be any updates on this?
