### ISSUE TITLE
UnboundLocalError: local variable 'ext' referenced before assignment

### ISSUE THREAD

**Issue by ll7** [openai/retro#260]
## Issue summary

I am trying to install a rom and I get the following error:

```shell
roms$ python -m retro.import .
Traceback (most recent call last):
  File "/home/luttkule/anaconda3/envs/rl-test/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/luttkule/anaconda3/envs/rl-test/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/luttkule/anaconda3/envs/rl-test/lib/python3.9/site-packages/retro/import/__main__.py", line 4, in <module>
    main()
  File "/home/luttkule/anaconda3/envs/rl-test/lib/python3.9/site-packages/retro/scripts/import_path.py", line 21, in main
    known_hashes = retro.data.get_known_hashes()
  File "/home/luttkule/anaconda3/envs/rl-test/lib/python3.9/site-packages/retro/data/__init__.py", line 401, in get_known_hashes
    known_hashes[sha] = (game, ext, os.path.join(path(), curpath))
UnboundLocalError: local variable 'ext' referenced before assignment
```

This is the content of the directory:

```shell
roms$ ls
'Street Fighter II'\'' - Special Champion Edition (Europe).md'  'Street Fighter II'\'' - Special Champion Edition (Europe).zip'
```

I downlaoded and extracted the rom from https://wowroms.com/en/roms/sega-genesis-megadrive/download-street-fighter-ii-special-champion-edition-europe/26496.html

## System information

- [Operating system] Ubuntu 20.04
- [Python version] 3.9.10
- [Gym Retro version] 0.7.1

**Comment by ll7** [comment]
Thank you. 

It seems to me that the import is still not successful:

```shell
(rl-test) luttkule@LeLuGPC-u:/mnt/UHDD/git/rl-test/nicholas-renotte/streetfighter/roms$ ls
'Street Fighter II'\'' - Special Champion Edition (Europe).md'  'Street Fighter II'\'' - Special Champion Edition (Europe).zip'
(rl-test) luttkule@LeLuGPC-u:/mnt/UHDD/git/rl-test/nicholas-renotte/streetfighter/roms$ python -m retro.import .
Imported 0 games
(rl-test) luttkule@LeLuGPC-u:/mnt/UHDD/git/rl-test/nicholas-renotte/streetfighter/roms$ python -m retro.import 'Street Fighter II'\'' - Special Champion Edition (Europe).md'
Imported 0 games
(rl-test) luttkule@LeLuGPC-u:/mnt/UHDD/git/rl-test/nicholas-renotte/streetfighter/roms$ python -m retro.import .
Imported 0 games
(rl-test) luttkule@LeLuGPC-u:/mnt/UHDD/git/rl-test/nicholas-renotte/streetfighter/roms$ python -m retro.import Street\ Fighter\ II\'\ -\ Special\ Champion\ Edition\ \(Europe\).md
Imported 0 games
```

**Comment by onaclov2000** [comment]
I'm not 100% sure but did you make sure your rom.sha matches the file you downloaded? If not you might need to update/create a rom.sha file.
