### ISSUE TITLE
Installation error in windows 10

### ISSUE THREAD

**Issue by ShuvenduBikash** [openai/retro#45]
## Issue summary

Following error message is given during installation

```
 File "C:\Users\bikas\gym-retro\setup.py", line 46, in run
        pip.main(['install', 'cmake'])
    AttributeError: module 'pip' has no attribute 'main'

    ----------------------------------------
Command "c:\users\bikas\anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\bikas\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Users\bikas\gym-retro\
```

## System information

- Windows 10
- Python 3.5.2
- Gym Retro 0.5.4

**Comment by endrift** [comment]
What version of setuptools do you have?

**Comment by ShuvenduBikash** [comment]
39.2.0

**Comment by ShuvenduBikash** [comment]
I updated the cmake and it stated the installation. But gave the following error.

```
Installing collected packages: gym-retro
  Running setup.py develop for gym-retro
    Complete output from command c:\users\bikas\anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\bikas\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing gym_retro.egg-info\PKG-INFO
    writing requirements to gym_retro.egg-info\requires.txt
    writing dependency_links to gym_retro.egg-info\dependency_links.txt
    writing top-level names to gym_retro.egg-info\top_level.txt
    package init file 'data\__init__.py' not found (or not a regular file)
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*-version' found under directory 'retro\cores'
    writing manifest file 'gym_retro.egg-info\SOURCES.txt'
    running build_ext
    -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users/bikas/gym-retro
    [ 90%] Built target zip
    [ 90%] Built target atari2600-submodule
    [ 90%] Built target atari2600
    [ 90%] Built target genesis-submodule
    [ 90%] Built target genesis
    [100%] Built target retro-base
    [100%] Building CXX object CMakeFiles/retro.dir/src/retro.cpp.obj
    In file included from C:/Users/bikas/gym-retro/src/retro.cpp:12:0:
    C:/Users/bikas/gym-retro/third-party/pybind11/include/pybind11/numpy.h:35:1: error: static assertion failed: ssize_t != Py_intptr_t
     static_assert(sizeof(ssize_t) == sizeof(Py_intptr_t), "ssize_t != Py_intptr_t");
     ^~~~~~~~~~~~~
    make[3]: *** [CMakeFiles/retro.dir/src/retro.cpp.obj] Error 1
    make[2]: *** [CMakeFiles/retro.dir/all] Error 2
    make[1]: *** [CMakeFiles/retro.dir/rule] Error 2
    make: *** [retro] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bikas\gym-retro\setup.py", line 77, in <module>
        use_scm_version=use_scm_version
      File "c:\users\bikas\anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\bikas\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\bikas\anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\bikas\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\bikas\anaconda3\lib\site-packages\setuptools\command\develop.py", line 36, in run
        self.install_for_development()
      File "c:\users\bikas\anaconda3\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "c:\users\bikas\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\bikas\anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\bikas\gym-retro\setup.py", line 55, in run
        subprocess.check_call(['make'] + jobs + ['retro'])
      File "c:\users\bikas\anaconda3\lib\subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j8', 'retro']' returned non-zero exit status 2

    ----------------------------------------
Command "c:\users\bikas\anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\bikas\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Users\bikas\gym-retro\
```

**Comment by ShuvenduBikash** [comment]
Here is what happened.
This patched worked fine. I installed and tried this code

```
import retro
env = retro.make(game='SonicTheHedgehog-Genesis', state='GreenHillZone.Act1')
```

but got this error

```
  File "c:\users\bikas\gym-retro\retro\__init__.py", line 121, in make
    get_romfile_path(game)
  File "c:\users\bikas\gym-retro\retro\__init__.py", line 85, in get_romfile_path
    raise FileNotFoundError("No romfiles found for game: %s" % game)
FileNotFoundError: No romfiles found for game: SonicTheHedgehog-Genesis

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\bikas\gym-retro\retro\__init__.py", line 126, in make
    raise FileNotFoundError('Game not found: %s. Did you make sure to import the ROM?' % game)
FileNotFoundError: Game not found: SonicTheHedgehog-Genesis. Did you make sure to import the ROM?
```

I thought i shold run this instruction for updating submodule
```
git submodule deinit -f --all
rm -rf .git/modules
git submodule update --init
```
But the error did not go away.  So, i tried to install again. And got this big error message

```

Installing collected packages: gym-retro
  Found existing installation: gym-retro 0.5.5.dev16+gd15a741
    Uninstalling gym-retro-0.5.5.dev16+gd15a741:
      Successfully uninstalled gym-retro-0.5.5.dev16+gd15a741
  Running setup.py develop for gym-retro
    Complete output from command c:\users\bikas\anaconda3\python.exe -c "import                                                                                                                                                                                                setuptools, tokenize;__file__='C:\\Users\\bikas\\gym-retro\\setup.py';f=getattr(                                                                                                                                                                                               tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();                                                                                                                                                                                               exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing gym_retro.egg-info\PKG-INFO
    writing dependency_links to gym_retro.egg-info\dependency_links.txt
    writing requirements to gym_retro.egg-info\requires.txt
    writing top-level names to gym_retro.egg-info\top_level.txt
    package init file 'data\__init__.py' not found (or not a regular file)
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.o' found anywhere in distr                                                                                                                                                                                               ibution
    warning: no previously-included files matching '*.a' found anywhere in distr                                                                                                                                                                                               ibution
    warning: no previously-included files matching '*.dylib' found anywhere in d                                                                                                                                                                                               istribution
    warning: no previously-included files matching '*.so' found anywhere in dist                                                                                                                                                                                               ribution
    warning: no previously-included files matching '*-version' found under direc                                                                                                                                                                                               tory 'retro\cores'
    writing manifest file 'gym_retro.egg-info\SOURCES.txt'
    running build_ext
    -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users/bikas/gym-retro
    Scanning dependencies of target zip
    [  0%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/gladman-f                                                                                                                                                                                               crypt.c.obj
    [  0%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_add.c                                                                                                                                                                                               .obj
    [  0%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_add_d                                                                                                                                                                                               ir.c.obj
    [  0%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_add_e                                                                                                                                                                                               ntry.c.obj
    [  0%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_algor                                                                                                                                                                                               ithm_bzip2.c.obj
    [  4%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_algor                                                                                                                                                                                               ithm_deflate.c.obj
..................
.................
    [ 86%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_uncha                                                                                                                                                                                               nge_archive.c.obj
    [ 86%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_uncha                                                                                                                                                                                               nge_data.c.obj
    [ 86%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_utf-8                                                                                                                                                                                               .c.obj
    [ 86%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_sourc                                                                                                                                                                                               e_win32handle.c.obj
    In file included from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_so                                                                                                                                                                                               urce_win32handle.c:41:0:
    C:/Users/bikas/gym-retro/third-party/libzip/lib/zipwin32.h:39:0: warning: "_                                                                                                                                                                                               WIN32_WINNT" redefined
     #define _WIN32_WINNT 0x0501

    In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h                                                                                                                                                                                               :10:0,
                     from C:/msys64/mingw64/x86_64-w64-mingw32/include/wchar.h:9                                                                                                                                                                                               ,
                     from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_so                                                                                                                                                                                               urce_win32handle.c:35:
    C:/msys64/mingw64/x86_64-w64-mingw32/include/_mingw.h:232:0: note: this is t                                                                                                                                                                                               he location of the previous definition
     #define _WIN32_WINNT 0x502

    [ 86%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_sourc                                                                                                                                                                                               e_win32utf8.c.obj
    In file included from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_so                                                                                                                                                                                               urce_win32utf8.c:38:0:
    C:/Users/bikas/gym-retro/third-party/libzip/lib/zipwin32.h:39:0: warning: "_                                                                                                                                                                                               WIN32_WINNT" redefined
     #define _WIN32_WINNT 0x0501

    In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h                                                                                                                                                                                               :10:0,
                     from C:/msys64/mingw64/x86_64-w64-mingw32/include/stdio.h:9                                                                                                                                                                                               ,
                     from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_so                                                                                                                                                                                               urce_win32utf8.c:35:
    C:/msys64/mingw64/x86_64-w64-mingw32/include/_mingw.h:232:0: note: this is t                                                                                                                                                                                               he location of the previous definition
     #define _WIN32_WINNT 0x502

    [ 86%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_sourc                                                                                                                                                                                               e_win32w.c.obj
    In file included from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_so                                                                                                                                                                                               urce_win32w.c:38:0:
    C:/Users/bikas/gym-retro/third-party/libzip/lib/zipwin32.h:39:0: warning: "_                                                                                                                                                                                               WIN32_WINNT" redefined
     #define _WIN32_WINNT 0x0501

    In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h                                                                                                                                                                                               :10:0,
                     from C:/msys64/mingw64/x86_64-w64-mingw32/include/stdio.h:9                                                                                                                                                                                               ,
                     from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_so                                                                                                                                                                                               urce_win32w.c:35:
    C:/msys64/mingw64/x86_64-w64-mingw32/include/_mingw.h:232:0: note: this is t                                                                                                                                                                                               he location of the previous definition
     #define _WIN32_WINNT 0x502

    [ 90%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_rando                                                                                                                                                                                               m_win32.c.obj
    In file included from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_ra                                                                                                                                                                                               ndom_win32.c:35:0:
    C:/Users/bikas/gym-retro/third-party/libzip/lib/zipwin32.h:39:0: warning: "_                                                                                                                                                                                               WIN32_WINNT" redefined
     #define _WIN32_WINNT 0x0501

    In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h                                                                                                                                                                                               :10:0,
                     from C:/msys64/mingw64/x86_64-w64-mingw32/include/stdint.h:                                                                                                                                                                                               28,
                     from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/inc                                                                                                                                                                                               lude/stdint.h:9,
                     from C:/Users/bikas/gym-retro/third-party/libzip/zipconf.h:                                                                                                                                                                                               40,
                     from C:/Users/bikas/gym-retro/third-party/libzip/config.h:4                                                                                                                                                                                               ,
                     from C:/Users/bikas/gym-retro/third-party/libzip/lib/zipint                                                                                                                                                                                               .h:38,
                     from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_ra                                                                                                                                                                                               ndom_win32.c:34:
    C:/msys64/mingw64/x86_64-w64-mingw32/include/_mingw.h:232:0: note: this is t                                                                                                                                                                                               he location of the previous definition
     #define _WIN32_WINNT 0x502

    [ 90%] Building C object third-party/libzip/lib/CMakeFiles/zip.dir/zip_sourc                                                                                                                                                                                               e_win32a.c.obj
    In file included from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_so                                                                                                                                                                                               urce_win32a.c:38:0:
    C:/Users/bikas/gym-retro/third-party/libzip/lib/zipwin32.h:39:0: warning: "_                                                                                                                                                                                               WIN32_WINNT" redefined
     #define _WIN32_WINNT 0x0501

    In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h                                                                                                                                                                                               :10:0,
                     from C:/msys64/mingw64/x86_64-w64-mingw32/include/stdio.h:9                                                                                                                                                                                               ,
                     from C:/Users/bikas/gym-retro/third-party/libzip/lib/zip_so                                                                                                                                                                                               urce_win32a.c:35:
    C:/msys64/mingw64/x86_64-w64-mingw32/include/_mingw.h:232:0: note: this is t                                                                                                                                                                                               he location of the previous definition
     #define _WIN32_WINNT 0x502

    [ 90%] Linking C static library libzip.a
    [ 90%] Built target zip
    [ 90%] Built target atari2600-submodule
    [ 90%] Built target atari2600
    [ 90%] Built target genesis-submodule
    [ 90%] Built target genesis
    [ 90%] Generating third-party/luajit/src/libluajit.a
    HOSTCC    host/minilua.o
    HOSTLINK  host/minilua.exe
    DYNASM    host/buildvm_arch.h
    HOSTCC    host/buildvm.o
    HOSTCC    host/buildvm_asm.o
    HOSTCC    host/buildvm_peobj.o
    HOSTCC    host/buildvm_lib.o
    HOSTCC    host/buildvm_fold.o
    HOSTLINK  host/buildvm.exe
    BUILDVM   lj_vm.o
    CC        lj_gc.o
    BUILDVM   lj_ffdef.h
    CC        lj_err.o
    CC        lj_char.o
    BUILDVM   lj_bcdef.h
    CC        lj_bc.o
    CC        lj_obj.o
    CC        lj_str.o
    CC        lj_tab.o
    CC        lj_func.o
    CC        lj_udata.o
    CC        lj_meta.o
    CC        lj_debug.o
    CC        lj_state.o
    CC        lj_dispatch.o
    CC        lj_vmevent.o
    CC        lj_vmmath.o
    CC        lj_strscan.o
    CC        lj_api.o
    CC        lj_lex.o
    CC        lj_parse.o
    CC        lj_bcread.o
    CC        lj_bcwrite.o
    CC        lj_load.o
    CC        lj_ir.o
    CC        lj_opt_mem.o
    BUILDVM   lj_folddef.h
    CC        lj_opt_fold.o
    CC        lj_opt_narrow.o
    CC        lj_opt_dce.o
    CC        lj_opt_loop.o
    CC        lj_opt_split.o
    CC        lj_opt_sink.o
    CC        lj_mcode.o
    CC        lj_snap.o
    CC        lj_record.o
    CC        lj_crecord.o
    BUILDVM   lj_recdef.h
    CC        lj_ffrecord.o
    CC        lj_asm.o
    CC        lj_trace.o
    CC        lj_gdbjit.o
    CC        lj_ctype.o
    CC        lj_cdata.o
    CC        lj_cconv.o
    CC        lj_ccall.o
    CC        lj_ccallback.o
    CC        lj_carith.o
    CC        lj_clib.o
    CC        lj_cparse.o
    CC        lj_lib.o
    CC        lj_alloc.o
    CC        lib_aux.o
    BUILDVM   lj_libdef.h
    CC        lib_base.o
    CC        lib_math.o
    CC        lib_bit.o
    CC        lib_string.o
    CC        lib_table.o
    CC        lib_io.o
    CC        lib_os.o
    CC        lib_package.o
    CC        lib_debug.o
    CC        lib_jit.o
    CC        lib_ffi.o
    CC        lib_init.o
    AR        libluajit.a
    Scanning dependencies of target retro-base
    [ 90%] Building CXX object CMakeFiles/retro-base.dir/src/coreinfo.cpp.obj
    [ 90%] Building CXX object CMakeFiles/retro-base.dir/src/data.cpp.obj
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/emulator.cpp.obj
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/memory.cpp.obj
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/movie.cpp.obj
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/movie-bk2.cpp.obj
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/script.cpp.obj
    [100%] Building CXX object CMakeFiles/retro-base.dir/src/script-lua.cpp.obj
    [100%] Building CXX object CMakeFiles/retro-base.dir/src/zipfile.cpp.obj
    [100%] Linking CXX static library libretro-base.a
    [100%] Built target retro-base
    Scanning dependencies of target retro
    [100%] Building CXX object CMakeFiles/retro.dir/src/retro.cpp.obj
    [100%] Linking CXX shared library retro/_retro.pyd
    C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64                                                                                                                                                                                               -w64-mingw32/bin/ld.exe: cannot open output file retro/_retro.pyd: Permission de                                                                                                                                                                                               nied
    collect2.exe: error: ld returned 1 exit status
    make[3]: *** [retro/_retro.pyd] Error 1
    make[2]: *** [CMakeFiles/retro.dir/all] Error 2
    make[1]: *** [CMakeFiles/retro.dir/rule] Error 2
    make: *** [retro] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bikas\gym-retro\setup.py", line 77, in <module>
        use_scm_version=use_scm_version
      File "c:\users\bikas\anaconda3\lib\site-packages\setuptools\__init__.py",                                                                                                                                                                                                line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\bikas\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\bikas\anaconda3\lib\distutils\dist.py", line 955, in run_co                                                                                                                                                                                               mmands
        self.run_command(cmd)
      File "c:\users\bikas\anaconda3\lib\distutils\dist.py", line 974, in run_co                                                                                                                                                                                               mmand
        cmd_obj.run()
      File "c:\users\bikas\anaconda3\lib\site-packages\setuptools\command\develo                                                                                                                                                                                               p.py", line 36, in run
        self.install_for_development()
      File "c:\users\bikas\anaconda3\lib\site-packages\setuptools\command\develo                                                                                                                                                                                               p.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "c:\users\bikas\anaconda3\lib\distutils\cmd.py", line 313, in run_com                                                                                                                                                                                               mand
        self.distribution.run_command(command)
      File "c:\users\bikas\anaconda3\lib\distutils\dist.py", line 974, in run_co                                                                                                                                                                                               mmand
        cmd_obj.run()
      File "C:\Users\bikas\gym-retro\setup.py", line 55, in run
        subprocess.check_call(['make'] + jobs + ['retro'])
      File "c:\users\bikas\anaconda3\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j8', 'retro']' returned n                                                                                                                                                                                               on-zero exit status 2.

    ----------------------------------------
  Rolling back uninstall of gym-retro
Command "c:\users\bikas\anaconda3\python.exe -c "import setuptools, tokenize;__f                                                                                                                                                                                               ile__='C:\\Users\\bikas\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(                                                                                                                                                                                               __file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __fil                                                                                                                                                                                               e__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Users\bikas\gym                                                                                                                                                                                               -retro\

```

**Comment by endrift** [comment]
```
FileNotFoundError: Game not found: SonicTheHedgehog-Genesis. Did you make sure to import the ROM?
```

This is not a build error. This means you (usually) didn't import the ROM; it's not included.

**Comment by Cosmono** [comment]
Got this same issue on my platform. Win 10 + Python 3.5 .
Still working on it.

**Comment by Cosmono** [comment]
C:\Users\wrxus\gym-retro\gym-retro\gym-retro>pip3 install -e .
Obtaining file:///C:/Users/wrxus/gym-retro/gym-retro/gym-retro
Requirement already satisfied: gym in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from gym-retro==0.5.5.dev17+g4840cf6) (0.10.5)
Requirement already satisfied: six in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from gym->gym-retro==0.5.5.dev17+g4840cf6) (1.11.0)
Requirement already satisfied: pyglet>=1.2.0 in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from gym->gym-retro==0.5.5.dev17+g4840cf6) (1.3.2)
Requirement already satisfied: numpy>=1.10.4 in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from gym->gym-retro==0.5.5.dev17+g4840cf6) (1.14.2)
Requirement already satisfied: requests>=2.0 in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from gym->gym-retro==0.5.5.dev17+g4840cf6) (2.18.4)
Requirement already satisfied: future in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from pyglet>=1.2.0->gym->gym-retro==0.5.5.dev17+g4840cf6) (0.16.0)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from requests>=2.0->gym->gym-retro==0.5.5.dev17+g4840cf6) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from requests>=2.0->gym->gym-retro==0.5.5.dev17+g4840cf6) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from requests>=2.0->gym->gym-retro==0.5.5.dev17+g4840cf6) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\wrxus\downloads\coding\python35\lib\site-packages (from requests>=2.0->gym->gym-retro==0.5.5.dev17+g4840cf6) (2018.4.16)
Installing collected packages: gym-retro
  Found existing installation: gym-retro 0.5.4
    Uninstalling gym-retro-0.5.4:
      Successfully uninstalled gym-retro-0.5.4
  Running setup.py develop for gym-retro
    Complete output from command c:\users\wrxus\downloads\coding\python35\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\wrxus\\gym-retro\\gym-retro\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing top-level names to gym_retro.egg-info\top_level.txt
    writing gym_retro.egg-info\PKG-INFO
    writing dependency_links to gym_retro.egg-info\dependency_links.txt
    writing requirements to gym_retro.egg-info\requires.txt
    package init file 'data\__init__.py' not found (or not a regular file)
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*-version' found under directory 'retro\cores'
    writing manifest file 'gym_retro.egg-info\SOURCES.txt'
    running build_ext
    -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users/wrxus/gym-retro/gym-retro/gym-retro
    [ 90%] Built target zip
    [ 90%] Built target atari2600-submodule
    [ 90%] Built target genesis-submodule
    [ 90%] Built target atari2600
    [ 90%] Built target genesis
    [100%] Built target retro-base
    [100%] Building CXX object CMakeFiles/retro.dir/src/retro.cpp.obj
    In file included from C:/Users/wrxus/gym-retro/gym-retro/gym-retro/src/retro.cpp:12:0:
    C:/Users/wrxus/gym-retro/gym-retro/gym-retro/third-party/pybind11/include/pybind11/numpy.h:35:1: error: static assertion failed: ssize_t != Py_intptr_t
     static_assert(sizeof(ssize_t) == sizeof(Py_intptr_t), "ssize_t != Py_intptr_t");
     ^~~~~~~~~~~~~
    make[3]: *** [CMakeFiles/retro.dir/build.make:64: CMakeFiles/retro.dir/src/retro.cpp.obj] Error 1
    make[2]: *** [CMakeFiles/Makefile2:376: CMakeFiles/retro.dir/all] Error 2
    make[1]: *** [CMakeFiles/Makefile2:388: CMakeFiles/retro.dir/rule] Error 2
    make: *** [Makefile:292: retro] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\wrxus\gym-retro\gym-retro\gym-retro\setup.py", line 77, in <module>
        use_scm_version=use_scm_version
      File "c:\users\wrxus\downloads\coding\python35\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\wrxus\downloads\coding\python35\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\wrxus\downloads\coding\python35\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\wrxus\downloads\coding\python35\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\wrxus\downloads\coding\python35\lib\site-packages\setuptools\command\develop.py", line 36, in run
        self.install_for_development()
      File "c:\users\wrxus\downloads\coding\python35\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "c:\users\wrxus\downloads\coding\python35\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\wrxus\downloads\coding\python35\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\wrxus\gym-retro\gym-retro\gym-retro\setup.py", line 55, in run
        subprocess.check_call(['make'] + jobs + ['retro'])
      File "c:\users\wrxus\downloads\coding\python35\lib\subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j4', 'retro']' returned non-zero exit status 2

    ----------------------------------------
  Rolling back uninstall of gym-retro
Command "c:\users\wrxus\downloads\coding\python35\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\wrxus\\gym-retro\\gym-retro\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Users\wrxus\gym-retro\gym-retro\gym-retro\

**Comment by ftrier** [comment]
I solved it by applying following patch:
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ebc5c0c..d47dbe6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -258,7 +258,7 @@ if(BUILD_PYTHON)
     if(APPLE)
         set(PYBIND_LIBS "-undefined dynamic_lookup")
     elseif(WIN32)
-        if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
+        if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
             add_definitions(-DMS_WIN64)
         endif()
         set(PYBIND_LIBS "${PYTHON_LIBRARY}")
```

**Comment by christopherhesse** [comment]
This appears to have already been added to CMakeLists.txt, @endrift want to close this issue if that's the case?

**Comment by reginalluna** [comment]
I have the same problem
