### ISSUE TITLE
random-agent.py works but random-agent-contest.py not working

### ISSUE THREAD

**Issue by HanSeoulOh** [openai/retro#5]
## Issue summary
Traceback (most recent call last):
  File "random-agent-contest.py", line 15, in <module>
    main()
  File "random-agent-contest.py", line 8, in main
    obs, rew, done, info = env.step(env.action_space.sample())
  File "C:\Users\Han\AppData\Local\conda\conda\envs\openairetro\lib\site-packages\gym\wrappers\time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "c:\openairetro\retro-contest\support\retro_contest\__init__.py", line 33, in step
    ob, rew, done, info = self.env.step(self.curac)
  File "C:\Users\Han\AppData\Local\conda\conda\envs\openairetro\lib\site-packages\retro\retro_env.py", line 172, in step
    rew, done, info = self.compute_step(ob)
  File "C:\Users\Han\AppData\Local\conda\conda\envs\openairetro\lib\site-packages\retro\retro_env.py", line 20, in compute_step
    reward = self.data.current_reward()
RuntimeError: Lua call failed: attempt to call a nil value

## System information

- Win10
- Py3.5

**Comment by endrift** [comment]
Fixed in https://github.com/openai/retro/commit/8a20c0f2927a5cd5030b1eaf1f262f18e652e5b8.
