### ISSUE TITLE
RuntimeError: Could not load movie

### ISSUE THREAD

**Issue by zacbraddy** [openai/retro#55]
## Issue summary

So I managed to jump through a not insignificant number of hoops to get gym retro up and running on my windows machine. Finally got it up and running and I can run the record and playback scripts without any errors. One thing that may or may not be worth mentioning is that on playback nothing opens; as in no windows open and playback the game or anything. I haven't used gym retro yet so I'm unsure if this is normal or not. I can see the python process is doing something but, as I said, there is no visual representation of this is show. I'm unsure if this is related to the problem but I thought it worth pointing out.

Another thing that might be worth mentioning is that I sourced my Sonic The Hedgehog 1 ROM and it was successfully imported according to the messages I got from the import command. When I imported the ROM I did so from the D:\Projects\gym-retro folder. I have a folder within that folder called `Sonic The Hedgehog` I got the following output from the import command:

```
> python -m retro.import "Sonic The Hedgehog
Importing 54 potential games...
Importing SonicTheHedgehog-Genesis
Imported 1 games
```

At First when I tried to run the playback_movie script I got the following:

```
> python .\scripts\playback_movie.py SonicTheHedgehog-Genesis-GreenHillZone-000000.bk2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Program Files\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Program Files\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Program Files\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Program Files\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Projects\gym-retro\scripts\playback_movie.py", line 4, in <module>
    main()
  File "d:\projects\gym-retro\retro\scripts\playback_movie.py", line 221, in main
    list(pool.map(_play, *zip(*[(movie, args, monitor_csv) for movie in args.movies])))
  File "D:\Program Files\Python36\lib\concurrent\futures\process.py", line 496, in map
    timeout=timeout)
  File "D:\Program Files\Python36\lib\concurrent\futures\_base.py", line 575, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "D:\Program Files\Python36\lib\concurrent\futures\_base.py", line 575, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "D:\Program Files\Python36\lib\concurrent\futures\process.py", line 466, in submit
    self._start_queue_management_thread()
  File "D:\Program Files\Python36\lib\concurrent\futures\process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "D:\Program Files\Python36\lib\concurrent\futures\process.py", line 446, in _adjust_process_count
    p.start()
  File "D:\Program Files\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Program Files\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Program Files\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Program Files\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Program Files\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\Program Files\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File ".\scripts\playback_movie.py", line 4, in <module>
    main()
  File "d:\projects\gym-retro\retro\scripts\playback_movie.py", line 221, in main
    list(pool.map(_play, *zip(*[(movie, args, monitor_csv) for movie in args.movies])))
  File "D:\Program Files\Python36\lib\concurrent\futures\process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "D:\Program Files\Python36\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "D:\Program Files\Python36\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "D:\Program Files\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

I did as the error suggested and added the code:

```python
if __name__ == '__main__'
```

Just above the call to `main()` in the scripts/playback_movie.py file. After I did that the message I get when I try to run the export to movie command given in the README.md is the following:

```
$ python scripts/playback_movie.py SonicTheHedgehog-Genesis-GreenHillZone-000000.bk2
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "d:\projects\gym-retro\retro\scripts\playback_movie.py", line 183, in _play
    emulator, m, duration = load_movie(movie)
  File "d:\projects\gym-retro\retro\scripts\playback_movie.py", line 152, in load_movie
    movie = retro.Movie(movie_file)
RuntimeError: Could not load movie

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\Program Files\Python36\lib\concurrent\futures\process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "D:\Program Files\Python36\lib\concurrent\futures\process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "d:\projects\gym-retro\retro\scripts\playback_movie.py", line 196, in _play
    del emulator
UnboundLocalError: local variable 'emulator' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/playback_movie.py", line 5, in <module>
    main()
  File "d:\projects\gym-retro\retro\scripts\playback_movie.py", line 222, in main
    list(pool.map(_play, *zip(*[(movie, args, monitor_csv) for movie in args.movies])))
  File "D:\Program Files\Python36\lib\concurrent\futures\process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "D:\Program Files\Python36\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "D:\Program Files\Python36\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "D:\Program Files\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
UnboundLocalError: local variable 'emulator' referenced before assignment
```

Again, I'm running this command from D:\Projects\gym-retro and this is where the `SonicTheHedgehog-Genesis-GreenHillZone-000000.bk2` file is. Worth noting that the name of the file is different to the one used in the README.md this is because the record created this different file name when I recorded it that file does exists with that file name in the root of retro-gym.

I thought maybe it couldn't find the file because it was executing from the scripts folder so I also tried prepending `../` to the `.bk2` filename but to no avail. I've also tried printing out the value of `movie_file` at the start of the `load_movie` method and the variable is populate correctly.

I'm now official out of ideas and I'm hoping that someone might be able to help to find other avenues to explore to solve this problem. Thanks in advance for you time and effort, I really appreciate it.

## System information

- Windows 10
- 3.6.6 <-- worth noting I had to downgrade pip3 to 9.0.3 to get the install of gym retro working
- 0.5.6

**Comment by endrift** [comment]
There was a bug for a while whereby generated bk2s would be corrupted. Can I see your bk2 files?

**Comment by zacbraddy** [comment]
Sure man, here you go:
[From my google drive](https://drive.google.com/open?id=1keLEQXajbZEEBy8uh6v5PPsoMvkOT7gF)

**Comment by endrift** [comment]
Ok, this one doesn't appear to be corrupted. Will take a closer look.

**Comment by endrift** [comment]
Seems to work for me, though that second error is (obliquely) indicative of the file not being found.

**Comment by endrift** [comment]
Also make sure ffmpeg is installed and in PATH. This script is for converting to .mp4, which it does via ffmpeg. If you want a realtime view you can use the `-v` option (but you'll need to pass it a player utility)

**Comment by zacbraddy** [comment]
Right so I installed ffmpeg and added to my path and everything has come to life so that's awesome! Thanks so much for you time and effort helping me sort this out I really appreciate it.

I didn't see anywhere in the README that suggested that ffmpeg was a prerequisite for rendering to video is it somewhere I just didn't see? If not would you like me to make a PR to add this info to the README? Maybe we can save others from falling into the same trap.

Also whilst I have your ear, when I run the playback script Python takes up some resources and obviously does a few things but I don't actually see any output from it. Is there any resources where I can read up about exactly what "playing back" means and what it's doing or if you have the time could you write a paragraph or two here explaining what that script is attempting to achieve? Because when I read playback I had assumed this was achieving essentially what the playback script with `-v` was achieving but apparently I'm mistaken. If I learn this maybe I could add it to my potential PR.

Thanks again

**Comment by endrift** [comment]
Yeah, there's a lot of stuff that's not clearly documented. I should make a list of what needs documentation still.
