### ISSUE TITLE
Cannot import Rom

### ISSUE THREAD

**Issue by ftrier** [openai/retro#66]
## Issue summary

I cannot import sonic from my steam library.
Whenever I try to import the folder or directly via the steam API, I receive:

> Importing 1 potential games...
> Traceback (most recent call last):
>   File "C:\Users\...\Anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\...\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\...\Anaconda3\envs\tensorflow\lib\site-packages\gym_retro-0.6.0.dev33+gb7ac383-py3.5-win-amd64.egg\retro\import\__main__.py", line 4, in <module>
>     main()
>   File "C:\Users\...\Anaconda3\envs\tensorflow\lib\site-packages\gym_retro-0.6.0.dev33+gb7ac383-py3.5-win-amd64.egg\retro\scripts\import_path.py", line 14, in main
>     retro.data.merge(*potential_roms, quiet=False)
>   File "C:\Users\...\Anaconda3\envs\tensorflow\lib\site-packages\gym_retro-0.6.0.dev33+gb7ac383-py3.5-win-amd64.egg\retro\data\__init__.py", line 355, in merge
>     known_hashes[sha] = (game, ext, os.path.join(path(), curpath))
> UnboundLocalError: local variable 'ext' referenced before assignment

## System information

I have Win10, Python 3.5.5 and the current github retro version.

**Comment by ftrier** [comment]
I made a workaround by reinstalling it:
1. I uninstalled the whole package from my anaconda environment.
2. Instead of running python setup.py install, I ran pip install -e.
3. I imported the rom.
4. I ran python setup.py install

Apparently, it was important to import the game before installing(copying) it into the anaconda environment.
