### ISSUE TITLE
Symbol not found: __Py_ZeroStruct

### ISSUE THREAD

**Issue by piclez** [openai/retro#75]
After installing successfully from source on MacOS (Python 3.6.5):

`import retro`

gives error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gym-retro/retro/__init__.py", line 2, in <module>
    import retro.data
  File "/gym-retro/retro/data/__init__.py", line 1, in <module>
    from retro._retro import GameDataGlue, RetroEmulator, data_path as _data_path
ImportError: dlopen(/gym-retro/retro/_retro.cpython-36m-darwin.so, 2): Symbol not found: __Py_ZeroStruct
  Referenced from: /gym-retro/retro/_retro.cpython-36m-darwin.so
  Expected in: flat namespace
 in /gym-retro/retro/_retro.cpython-36m-darwin.so
```

Any ideas please?

**Comment by endrift** [comment]
That means it used the Python 2 headers.

**Comment by piclez** [comment]
Hi @endrift thanks. How can I avoid that?
`brew ls --versions | grep python`
```boost-python 1.67.0
python 3.6.5_1 2.7.14
```

**Comment by endrift** [comment]
Delete the CMakeCache.txt and try rebuilding with a virtualenv.

**Comment by piclez** [comment]
Thanks I cloned it again and reinstalled and its working now. :)
