### ISSUE TITLE
TypeError when trying to run a custom ROM

### ISSUE THREAD

**Issue by DavidRandisi** [openai/retro#79]
## Issue summary

I have followed the official guide on how to run a custom ROM. I created a starting state, added variables to the game and imported the ROM. When I try to run this environment with:
`env = retro.make(game='Pitfall-Atari2600', state='state1')`
I get a TypeError:

> Traceback (most recent call last):
  File "clousedsource.py", line 2, in <module>
    env = retro.make(game='Pitfall-Atari2600', state='state1')
  File "/home/davidrandisi/gym-retro/retro/__init__.py", line 65, in make
    return RetroEnv(game, state, inttype=inttype, **kwargs)
  File "/home/davidrandisi/gym-retro/retro/retro_env.py", line 80, in __init__
    self.load_state(self.statename, inttype)
  File "/home/davidrandisi/gym-retro/retro/retro_env.py", line 269, in load_state
    with gzip.open(retro.data.get_file_path(self.gamename, statename, inttype), 'rb') as fh:
  File "/home/davidrandisi/anaconda3/lib/python3.5/gzip.py", line 57, in open
    raise TypeError("filename must be a str or bytes object, or a file")
TypeError: filename must be a str or bytes object, or a file

I was wondering if anyone knew how to fix this?

## System information

- [Operating system]
Ubuntu 16.04
- [Python version]
3.5.2
- [Gym Retro version]
0.6

**Comment by DavidRandisi** [comment]
Fixed by adjusting the starting state's filename. It didn't include a .state extension.
